name: Java CI - Form Automation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Instalar Google Chrome
        run: sudo apt-get update && sudo apt-get install -y google-chrome-stable

      - name: Instalar dependências
        run: mvn install -DskipTests=true

      - name: Rodar testes
        run: mvn test
